### PR TITLE
fixing is_installed() for 0.7 alpha

### PR DESCRIPTION
**Pull request by kafisatz**

### CODE REVIEW

**Comment by SimonDanisch** [comment]
```
Not installed: Test Failed at /home/travis/build/JuliaIO/FileIO.jl/test/error_handling.jl:19
  Expression: fetch07(ref)
    Expected: CompositeException
      Thrown: Pkg.Types.CommandError
```
This seems related to this PR?

**Comment by SimonDanisch** [comment]
hm, actually this is also present on master: https://travis-ci.org/JuliaIO/FileIO.jl/jobs/391157366

**Comment by kafisatz** [comment]
I am not sure about the TravisCI stuff you linked (because I have no experience with CI or Travis).
But loadsave.jl has 'using Pkg3' which throws an error on 0.7alpha. The code is present on master and I think it needs to be amended for it to run smoothly.

**Comment by timholy** [comment]
I think this is outdated now. Sorry for the inconvenience.

**Pull request closed without merging**
