### PR TITLE
Update REQUIRE

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by tkelman** [comment]
`take!` is used in `test/query.jl` so it's at least needed in `test/REQUIRE`

**Comment by musm** [comment]
What about https://github.com/JuliaIO/FileIO.jl/pull/95#discussion_r97010524 ?

**Comment by musm** [comment]
nvm

**Comment by tkelman** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/7617#discussion_r97072364

**Pull request closed without merging**
