### PR TITLE
remove newline check from Rdata

### LINKED ISSUE #82: Pkg.test() on windows with Julia-0.5 fails
```
julia> Pkg.test("FileIO")
INFO: Computing test dependencies for FileIO...
INFO: Installing FactCheck v0.4.3
INFO: Testing FileIO
FileIO
  > OS
  > DataFormat
  > streams
  > query
  > multiple libs
  > STL detection
  > PLY detection
  > Multiple Magic bytes
  > AVI Detection
  > RDA detection
    Failure :: (line:272) :: RDA detection :: fact was false
      Expression: FileIO.detect_rdata(io) --> true
        Expected: true
        Occurred: false
  > Format with function for magic bytes
  > Load
  > Save
  > Ambiguous extension
  > Absent file
  > Not installed
Library NotInstalled is not installed but can load format: FileIO.File{FileIO.Da
taFormat{:NotInstalled}}("test.not_installed")
should we install NotInstalled for you? (y/n):
Library NotInstalled is not installed but can load format: FileIO.File{FileIO.Da
taFormat{:NotInstalled}}("test.not_installed")
should we install NotInstalled for you? (y/n):
invalid is not a valid choice. Try typing y or n
should we install NotInstalled for you? (y/n):
Out of 99 total facts:
  Verified: 98
  Failed:   1
ERROR: LoadError: FactCheck finished with 1 non-successful tests.
 in exitstatus() at C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0.5.0.1\v
0.5\FactCheck\src\FactCheck.jl:568
 in include_from_node1(::String) at .\loading.jl:488
 in process_options(::Base.JLOptions) at .\client.jl:262
 in _start() at .\client.jl:318
while loading C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\pkgs-0.5.0.1\v0.5\Fi
leIO\test\runtests.jl, in expression starting on line 10
===============================[ ERROR: FileIO ]================================


failed process: Process(`'C:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\Julia-0.
5.0\bin\julia' -Cx86-64 '-JC:\Users\julia\AppData\Local\JuliaPro-0.5.0.1\Julia-0
.5.0\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-co
verage=none --color=yes --compilecache=yes 'C:\Users\julia\AppData\Local\JuliaPr
o-0.5.0.1\pkgs-0.5.0.1\v0.5\FileIO\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================

INFO: Removing FactCheck v0.4.3
ERROR: FileIO had test errors
 in #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at .\pkg\entry.jl:74
0
 in (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array
{AbstractString,1}) at .\<missing>:0
 in (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstract
String,1}}})() at .\pkg\dir.jl:31
 in cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{Abstra
ctString,1}}}, ::String) at .\file.jl:48
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::V
ararg{Array{AbstractString,1},N}) at .\pkg\dir.jl:31
 in (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::A
rray{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at .\<missing>:0
 in #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at .\pkg\pkg.jl:25
8
 in test(::String, ::Vararg{String,N}) at .\pkg\pkg.jl:258
```

### PR DESCRIPTION
**Pull request by simonbyrne**
Should hopefully fix #82 

@alyst, would you mind taking a look at this?

### CODE REVIEW

**Comment by alyst** [comment]
The problem is, `detect_rdata()` is used by `RData.load()` to skip the magic bytes including the newline, so if `0x0A` is not read, `load()` should fail.

I must admit I don't know the Julia windows IO specifics. Is there a way to actually read the newline, or at least to make sure that io position is after the newline for all OSs?

**Comment by simonbyrne** [comment]
I've added a more complicated check, though this is also equivalent to that proposed in #83 (I didn't realise it was already there).

**Comment by SimonDanisch** [comment]
Oh no, this happens when you put two prs into one... Didn't expect the abspath to block this... Shall we just merge this one?!

**Comment by alyst** [comment]
LGTM

**Comment by SimonDanisch** [comment]
Great, thanks! :)

**Pull request merged**
