### PR TITLE
Register parquet file format

### PR DESCRIPTION
**Pull request by davidanthoff**
Don't merge yet, we still need to tag and register a whole bunch of packages upstream before this is ready.

### CODE REVIEW

**Comment by davidanthoff** [comment]
This is now ready to be merged. CC @timholy or @SimonDanisch.

**Comment by davidanthoff** [comment]
Bump, @timholy or @SimonDanisch, could this be merged? Thanks!

**Comment by SimonDanisch** [comment]
Sorry for ignoring this!

**Comment by davidanthoff** [comment]
No, worries, thanks!

**Comment by davidanthoff** [comment]
Oh, and could you also tag a release? :)

**Pull request merged**
