### PR TITLE
Fix detect_compressed()

### PR DESCRIPTION
**Pull request by alyst**
The PR fixes a typo in BZIP2 magic bytes that is responsible for JuliaData/RData.jl#83 and adds unit tests for all supported compression formats.

I've also refactored the compression detection: now there is `detect_compressor()` function that returns the compression format code or *nothing* if no supported format detected.
I would be using it from *RData.jl* instead of the compression detection code that is currently there to avoid code duplication.
Also, it could help in future when implementing the format detection of decompressed streams.
For example, the current version of *FileIO* checks for *RData*-specific magic bytes if the file is not compressed, but for compressed *RData* files it just checks the compression format but skips magic bytes check of the uncompressed stream (see also #225).

Once merged, it would be nice to tag a new version of *FileIO*, because the fix of JuliaData/RData.jl#83 depends on it.

### CODE REVIEW

**Comment by alyst** [comment]
@timholy could you please take a look?

**Review by johnnychen94 — APPROVED** [review]
Curious to ask, will it be better to use `:GZIP`, `:BZIP2`, `:XZ`, `:LZ4` and perhaps `:plain` (or `:uncompressed`) here?

**Comment by johnnychen94** [comment]
> Once merged, it would be nice to tag a new version of FileIO, because the fix of JuliaData/RData.jl#83 depends on it.

FileIO v1.6.5 is out.

**Comment by alyst** [comment]
> Curious to ask, will it be better to use `:GZIP`, `:BZIP2`, `:XZ`, `:LZ4` and perhaps `:plain` (or `:uncompressed`) here?

Thanks for merging!
I think returning `:uncompressed` would be misleading as we only check a limited subset of compressors.
I don't have a particular preference to symbols or strings, I've just kept the current choice.

**Pull request merged**
