### PR TITLE
Register GSLIB file format

### PR DESCRIPTION
**Pull request by juliohm**
I am proposing (and coding) an extension to the file format introduced in http://gslib.com

### CODE REVIEW

**Comment by juliohm** [comment]
Do I need to have it working before you can merge this?

**Comment by SimonDanisch** [comment]
Yes, I thought that was the plan from your side as well ;)
There's not much use for a file format without a loader.

**Comment by juliohm** [comment]
Hi @SimonDanisch , I finished the first version of the package, I just want to make sure everything is in place before I register it. The tests in Travis are failing, can you please review the code to see if I did something incorrectly?

https://github.com/juliohm/GslibIO.jl

Also, can you confirm that a user doesn't need to install my package to read/write the format, everything is managed indirectly by `FileIO.jl`? If that is the case I will remove the installation section from the README.

**Comment by juliohm** [comment]
Can anyone give a hand on this?

**Comment by SimonDanisch** [comment]
it says undefined variable error, which is because you're using an undefined variable in one of your last statements. It's a typo I assume.

**Comment by juliohm** [comment]
@SimonDanisch I fixed the issue, I think now the only problem is that the format is not registered yet with FileIO, can you please confirm?

**Comment by SimonDanisch** [comment]
Did you confirm it locally by running the tests on this branch?

**Comment by juliohm** [comment]
I'm gonna double check locally...

-Júlio

**Comment by SimonDanisch** [comment]
It'd be nice if you test your code yourself before committing :P 
But you're using it wrong. You must test it like this:
```Julia
using FileIO

array = load("test.gslib")
array = save("test.gslib")
```
Otherwise fileio can't do it's magic...

**Comment by juliohm** [comment]
Fixed, tests pass locally now, can you please review?

**Comment by SimonDanisch** [comment]
Okay, that error message looks more like it!
After merging, you can temporarily add a Pkg.checkout("FileIO") into your tests to be sure that things work before tagging a new FileIO version.

**Comment by juliohm** [comment]
Thanks @SimonDanisch , I will checkout FileIO locally and let you know.

**Pull request merged**
