### PR TITLE
Add support for OpenCV.jl

### PR DESCRIPTION
**Pull request by rakeshksr**
OpenCV.jl read and write several image [formats](https://docs.opencv.org/4.x/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56).

This PR covers major image formats.

### CODE REVIEW

**Review by sjkelly — APPROVED** [review]

**Comment by rakeshksr** [comment]
@sjkelly Could you please let me know what is preventing this pull request from being merged?
FYI,  JuliaImages/OpenCV.jl#35 waiting for this PR.

**Comment by sjkelly** [comment]
Just a friendly reminder, thanks! :)

**Comment by rakeshksr** [comment]
@sjkelly  Would it be possible to initiate a new release incorporating this pr.
FYI, https://github.com/JuliaImages/OpenCV.jl/pull/35 waiting for this PR.

**Comment by rakeshksr** [comment]
Thanks for the information and Happy New Year.

**Pull request merged**
