### PR TITLE
Bedgraph files

### PR DESCRIPTION
**Pull request by CiaranOMara**
Please register [BedgraphFiles](https://github.com/CiaranOMara/BedgraphFiles.jl) for use with .bedgraph files.

### CODE REVIEW

**Comment by timholy** [comment]
Are there no magic bytes one can use?

**Comment by CiaranOMara** [comment]
I've honestly no idea. How would one find out?

Bedgraph files predominantly hold tab separated values, and the first few lines of the file are inconsistent or unenforced ([https://genome.ucsc.edu/goldenPath/help/bedgraph.html](https://genome.ucsc.edu/goldenPath/help/bedgraph.html))

**Comment by CiaranOMara** [comment]
I reopened this pull request as #149.

**Comment by CiaranOMara** [comment]
I had not seen this before, anyhow, the link provided above specifies that a bedGraph file is supposed to contain the string `type=bedGraph` within the track definition. Can this information be converted to magic bytes?

**Comment by CiaranOMara** [comment]
@timholy, according to the screenshot below, would the following be the magic bytes?

`[0x74, 0x79, 0x70, 0x65, 0x3D, 0x62, 0x65, 0x64, 0x47, 0x72, 0x61, 0x70, 0x68]`

screen shot 2017-08-28 at 4 45 37 pm

**Pull request closed without merging**
