### PR TITLE
break up query.jl into seperate files

### PR DESCRIPTION
**Pull request by oxinabox**
I was having trouble finding things in the package.
In particular I was looking for the `Stream` type, and couldn't find it.

I think this is a bit of a cleaner restructuring of the files.

No features have been added or removed it is just code being moved around.

### CODE REVIEW

**Comment by Tokazama** [comment]
I agree that this is a nicer way of organizing things.

**Comment by oxinabox** [comment]
Bump

**Comment by SimonDanisch** [comment]
Thank you ;) Looks good to me! @timholy, what do you think ?

**Comment by SimonDanisch** [comment]
Thank you :)

**Pull request merged**
